server {
    listen 80;
    server_name _;
    root /opt/bunker17/www;
    index index.html;

    gzip on;
    gzip_types text/html application/json;

    location /api/ {
        proxy_pass http://127.0.0.1:8017;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }
}
